<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\GibbsMin.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Data\H2AirInp.json" />
    <None Remove="Data\moleculeJson.json" />
    <None Remove="Data\NASA.json" />
    <None Remove="Data\NASApolynomials.json" />
    <None Remove="Data\newShortThermo.json" />
    <None Remove="Data\refElements.json" />
    <None Remove="Data\Ref_Defaults.json" />
    <None Remove="Data\shortThermo.json" />
    <None Remove="Data\shortTrans.json" />
    <None Remove="Data\tableOfElements.json" />
    <None Remove="Data\TempSchedule.json" />
    <None Remove="Data\thermoINP.json" />
    <None Remove="Data\transINP.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\H2AirInp.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\NASA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\moleculeJson.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\NASApolynomials.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\newShortThermo.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\refElements.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\Ref_Defaults.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\shortThermo.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\shortTrans.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\tableOfElements.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\TempSchedule.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\thermoInp.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\transINP.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Accord" Version="3.8.2-alpha" />
    <PackageReference Include="Accord.Math" Version="3.8.2-alpha" />
    <PackageReference Include="MathNet.Numerics" Version="6.0.0-beta1" />
    <PackageReference Include="MathNet.Symbolics" Version="0.25.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="ScottPlot" Version="5.0.21" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ThermoChemistry\Optimizers\" />
  </ItemGroup>

</Project>
